name: "Create Keystore Properties"
description: "Create Keystore Properties"
inputs:
  keystore:
    description: "keystore"
    required: false
    default: "keystore"
  keystore-properties:
    description: "keystore properties"
    required: false
    default: "keystore.properties"
  release-key-alias:
    description: "releaseKeyAlias"
    required: true
  release-key-password:
    description: "releaseKeyPassword"
    required: true
  release-store-password:
    description: "releaseStorePassword"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "releaseKeyAlias=${{ inputs.release-key-alias }}" > ${{ inputs.keystore-properties }}
      shell: bash
    - run: echo "releaseKeyPassword=${{ inputs.release-key-password }}" >> ${{ inputs.keystore-properties }}
      shell: bash
    - run: echo "releaseKeyStore=${{ inputs.keystore }}" >> ${{ inputs.keystore-properties }}
      shell: bash
    - run: echo "releaseStorePassword=${{ inputs.release-store-password }}" >> ${{ inputs.keystore-properties }}
      shell: bash