name: "Build And Archive"
description: "Build And Archive"
inputs:
  version-number:
    description: "version number"
    required: false
    default: ${{ github.run_number }}
  slack-token:
    description: "slack token"
    required: false
    default: ${{ secrets.SLACK_TOKEN }}
  slack-webhook-url:
    description: "slack webhook url"
    required: false
    default: ${{ secrets.SLACK_WEBHOOK_URL }}
  slack-channel-id:
    description: "slack channel id"
    required: false
    default: ${{ secrets.SLACK_CHANNEL_ID }}
  apk-path:
    description: "apk path"
    required: false
    default: "app/build/outputs/apk/release"
  apk-name:
    description: "apk name"
    required: false
    default: "${{ vars.APP_NAME }}-${{ inputs.version-number }}.apk"
runs:
  using: "composite"
  steps:
    - run: ./gradlew assembleRelease
      shell: bash
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,ref # repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
      if: always()
    - name: Change File Name
      run: mv ${{ inputs.apk-path }}/app-release.apk ${{ inputs.apk-path }}/${{ inputs.apk-name }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.apk-name }}
        path: ${{ inputs.apk-path }}/*.apk
    - name: Slack Upload Artifacts
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ inputs.slack-token }}
        channel_id: ${{ inputs.slack-channel-id }}
        file_path: '${{ inputs.apk-path }}/${{ inputs.apk-name }}'