# 정의 해야 할 것
# secrets:
#   APP_ID
#   BASE64_KEYSTORE
#   RELEASE_KEY_ALIAS
#   RELEASE_KEY_PASSWORD
#   RELEASE_STORE_PASSWORD
#   SLACK_CHANNEL_ID
#   SLACK_TOKEN
#   SLACK_WEBHOOK_URL
# vars:
#   APP_NAME

name: Build

on: push

env:
  JAVA_DISTRIBUTION: corretto
  JAVA_VERSION: 17
  COMPILE_SDK: 33
  MIN_SDK: 21
  TARGET_SDK: 33
  VERSION_CODE: ${{ github.run_number }}
  VERSION_NAME: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: ./.github/actions/chmod_permission
      - uses: ./.github/actions/decode-keystore
      - uses: ./.github/actions/create-keystore-properties
      - uses: ./.github/actions/install-android-gradle-dependencies
      - uses: ./.github/actions/check-dependency-updates
      - uses: ./.github/actions/create-build-properties
        with:
          compile-sdk: ${{ env.COMPILE_SDK }}
          min-sdk: ${{ env.MIN_SDK }}
          target-sdk: ${{ env.TARGET_SDK }}
          version-code: ${{ env.VERSION_CODE }}
          version-name: ${{ env.VERSION_NAME }}
      - uses: ./.github/actions/build_and_archive